### ISSUE TITLE
注册一两个号后无限错误

### ISSUE THREAD

**Issue by MicroWater** [MCQTSS/MCQTSS_4399register#4]
只成功了一两个号，之后无限报错
报错如下
Traceback (most recent call last):
  File "C:\Users\AtriMyDearMoments\Desktop\MCQTSS_4399register-main\auto_register_4399.py", line 70, in register_4399
    yzm_data = ocr.classification(
  File "C:\Users\AtriMyDearMoments\AppData\Local\Programs\Python\Python39\lib\site-packages\ddddocr\__init__.py", line 1590, in classification
    image = image.resize((int(image.size[0] * (64 / image.size[1])), 64), Image.ANTIALIAS).convert('L')
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

需要的环境与你readme中所述一致

**Comment by MicroWater** [comment]
破案了，是pillow版本过新，装回9.5.0版本后恢复正常了，最新版ANTIALIAS方法被删除了
