### ISSUE TITLE
注册两个后开始报错，后续无法注册账号

### ISSUE THREAD

**Issue by dhwfrebhcjew** [MCQTSS/MCQTSS_4399register#6]
代理:{'http': 'http://1.14.122.251:1080'}
代理:{'http': 'http://39.98.45.168:8081'}
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\MCQTSS_4399register-main\auto_register_4399.py", line 70, in register_4399
    yzm_data = ocr.classification(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\ddddocr\__init__.py", line 1590, in classification
    image = image.resize((int(image.size[0] * (64 / image.size[1])), 64), Image.ANTIALIAS).convert('L')
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

**Comment by MCQTSS** [comment]
报错原因为调用DDDDOCR异常导致
请尝试参考https://blog.csdn.net/light2081/article/details/131517132解决

**Comment by dhwfrebhcjew** [comment]
> 报错原因为调用DDDDOCR异常导致 请尝试参考 [https://blog.csdn.net/light2081/article/details/131517132 解决](https://blog.csdn.net/light2081/article/details/131517132%E8%A7%A3%E5%86%B3)

帖子没了

**Comment by MCQTSS** [comment]
https://blog.csdn.net/light2081/article/details/131517132

**Comment by dhwfrebhcjew** [comment]
> https://blog.csdn.net/light2081/article/details/131517132

代理:{'http': 'http://47.113.90.161:83'}
代理:{'http': 'http://180.97.87.63:80'}
代理:{'http': 'http://47.113.90.161:83'}
﻿<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
<script type="text/javascript">
        dd = document.domain.split('.');
        document.domain = dd[dd.length - 2] + '.' + dd[dd.length - 1];
</script>
<script type="text/javascript" src="//ptlogin.3304399.net/resource/cryptojs-aes.js?v=296"></script>
<script type="text/javascript" src="//ptlogin.3304399.net/resource/validation.js?v=296"></script>
<script type="text/javascript" src="//ptlogin.3304399.net/resource/messenger.js?v=296"></script>
<link rel="stylesheet" href="//ptlogin.3304399.net/resource/css/init.css?v=296" type="text/css"/>
<link rel="stylesheet" href="//ptlogin.3304399.net/resource/css/base.css?v=296" type="text/css"/>
</head>






<script type="text/javascript">
if (Messenger.shouldOpen) {
        var msnger = new Messenger({ target: window.parent });
}
</script>
<script>
        if(Messenger.shouldOpen){
                msnger.emit("isAutoRegSuccess",false);
        }else{
                window.parent.isAutoRegSuccess=false;
        }
                var isPhoneReg = false;
</script>


<body>

<div id='j-popLogin_box'  style="display:block;" >
                <div id="qq_login" class="login_qq login_logging clearfix">
                        <div class="ftip">其他登录</div>
                                <div class="clearfix folgin">
                                        <a id = "hr_label_phonelogin" href='javascript:eventHandles.showPopupPhoneLogin();' title="短信验证码登录" class="phone" target="_self"><i></i>短信验证码登录</a>
                                        <a id = "hr_label_qqlogin" href='javascript:eventHandles.toQzoneLogin(true);' title="QQ号登录" class="QQ" target="_self"><i></i>QQ登录</a>
                                        <a id = "hr_label_weixinlogin" href='javascript:eventHandles.toWeixinLogin(true);' title="微信登录" class="weixin" target="_self"><i></i>微信登录</a>
                                        <a id = "hr_label_weibologin" href='javascript:eventHandles.toWeiboLogin();' title="新浪微博登录" class="weibo" target="_self"><i></i>微博登录</a>
                                </div>
                        </div>
                </div>

        <div class="login_module w352" id="popup_reg_div">
                <div class="bd login_vertical">
                        <form onSubmit="return check_reg_new('Msg', 'j-password', 'j-passwordveri', reg_eula_agree);" id="reg_form" name="reg_form" method="post" action="/ptlogin/register.do">
                                <fieldset>
                                        <input type="hidden" name="postLoginHandler" value="default" />
                                        <input type="hidden" name="displayMode" value="popup" />
                                        <input type="hidden" name="bizId" value="" />
                                        <input type="hidden" id="appId" name="appId" value="www_home" />
                                        <input type="hidden" name="gameId" value="" />
                                        <input type="hidden" id="cid" name="cid" value="" />
                                        <input type="hidden" name="externalLogin" value="qq" />
                                        <input type="hidden" id="aid" name="aid" value="" />
                                        <input type="hidden" id="ref" name="ref" value="" />
                                        <input type="hidden" name="css" value="" />
                                        <input type="hidden" name="redirectUrl" value="" />
                                        <input type="hidden" id="regMode" name="regMode" value="reg_normal" />
                                        <input type="hidden" name="sessionId" value="captchaReq7c0bca4caf072159886" />
                                        <input type="hidden" name="regIdcard" value="true" />
                                        <input type="hidden" name="noEmail" value="" />
                                        <input type="hidden" name="crossDomainIFrame" value="" />
                                        <input type="hidden" name="crossDomainUrl" value="" />
                                        <input type="hidden" name="mainDivId" value="popup_reg_div" />
                                        <input type="hidden" name="showRegInfo" value="true" />
                                        <input type="hidden" name="includeFcmInfo" value="false" />
                                        <input type="hidden" name="expandFcmInput" value="true" />
                                    <input type="hidden" name="fcmFakeValidate" value="false" />
                                        <input type="hidden" name="realnameValidate" value="true" />
                                        <input type="hidden" name="userNameLabel" value="" />
                                        <input type="hidden" name="level" value="0" id="j-level"/>
                    <input type="hidden" name="sec" value="" id="j-sec"/>
                                        <input type="hidden" name="password" value="" id="j-psd"/>
                                        <input type="hidden" name="passwordveri" value="" id="j-psd-veri"/>
                                                <input type="hidden" name="realname" value="" id="j-xm-name"/>
                                                <input type="hidden" name="idcard" value="" id="j-xm-idcard"/>

                                        <div id="Msg" class="login_hor login_err_tip">
                                                身份证实名账号数量超过限制
                                        </div>
                                        <div class="login_hor clearfix">
                                                <label id = "rf_label_username"><em class="login_required"> *</em></label>
                                                <label id = "rf_label_simple_username"><em class="login_required"> *</em></label>
                                                <input type="text" style="visibility:hidden;position:fixed;float:left;width:0px;height:1px;"/>
                                                <input type="text" autocomplete="off" id="j-username"
                                                    name="username"
                                                        value="m594k1g"
                                                        checkstate="ok"
                                                        tip="用户名由3-20个字符组成" err="格式错误,必须由3~20个数字、字 母或“@”组成" class="login_ipt iptw2"
                                                        onfocus="showInputTip(this,regMode);if(document.getElementById('sendcode')){document.getElementById('sendcode').style.display='block';}"
                                                        onblur="
                                                                        if (''.length > 0 && this.value=='') {
                                                                                document.getElementById('j-username').setAttribute('checkstate', 'ok');
                                                                                document.getElementById('rf_label_usernametip').className='input_tip';
                                                                                document.getElementById('rf_label_usernametip').innerHTML='这是为您分配的账号,也可自己填写';
                                                                        } else {
                                                                                checkRegUsername(this, appId, regMode);
                                                                        }
                                                                "/>

                                                        <span class="input_tip" id = "rf_label_usernametip" ></span>
                                                        </div>


                                                <div class="login_hor clearfix">
                                                        <label id = "rf_label_password">密码<em class="login_required"> *</em></label>
                                                        <input type="password" id="j-password" value="ol0et3y2g7" autocomplete="new-password"  checkstate="ok" tip="长度为6-20个字符,区分大小写" err="格式错误，必须由6~20个字符组成" class="login_ipt iptw2"  onfocus="showInputTip(this)" />
                                                        <span class="input_tip" id = "rf_label_passwordtip"></span>
                                                </div>
                                                <div class="login_hor clearfix">
                                                        <label id = "rf_label_verifypasswd">再次输入密码<em class="login_required"> *</em></label>
                                                        <input  id="j-passwordveri" value="ol0et3y2g7" autocomplete="new-password" tip="" type="password" class="login_ipt iptw2"  err="两次密码不一致" value="" onfocus="showInputTip(this)" ／>
                                                        <span class="input_tip" id = "rf_label_verifypasswdtip"></span>
                                                </div>

                                                <div class="login_hor clearfix">
                                                        <label id = "rf_label_qqEmail">QQ号</label>
                                                        <input type="text" id="email" name="email" autocomplete="off" class="login_ipt iptw2" tip="(选填)可通过QQ号找回密码" err="不正确的qq号" checkstate="ok" value="mcqtssqb43z" onfocus="showInputTip(this)" onblur="checkRuleInput(this,'qq')"/>
                                                        <span class="input_tip" id = "rf_label_qqEmailtip">(选填)可通过QQ号找回密码</span>
                                                </div>

                                                <div class="login_hor clearfix">
                                                        <label id = "rf_label_realname">真实姓名<em class="login_required"> *</em></label>
                                                        <input type="text" id="j-realname" autocomplete="off" class="login_ipt iptw2"
                                                                checkstate="ok"
                                                                tip="防沉迷要求填写真实姓名"
                                                                err="不正确的真实姓名格式"
                                                                value="邓丽丹"
                                                                onfocus="showInputTip(this)"
                                                                onblur="checkInput(this,'realname',true, '水沧')"/>
                                                        <span class="input_tip" id = "rf_label_realnametip">防沉迷要求填写真实姓名</span>
                                                </div>
                                                <div class="login_hor clearfix">
                                                        <label id = "rf_label_cardid">身份证号<em class="login_required"> *</em></label>
                                                        <input type="text" id="j-idcard"  autocomplete="off" class="login_ipt iptw2"
                                                                checkstate="ok"
                                                                tip="<a href='https://u.4399.com/kf/im/zhrz?ref=www_home' target='_blank' class='howSetIdcard_link'>实名认证遇到问题？</a>"
                                                                err="不正确的身份证号"
                                                                value="450203198109121325"
                                                                onfocus="showInputTip(this)"
                                                                onblur="checkInput(this,'idcard', true, '42030219460727109X');"/>
                                                        <span class="input_tip" id = "rf_label_cardidtip"><a href='https://u.4399.com/kf/im/zhrz?ref=www_home' target='_blank' class='howSetIdcard_link'>实名认证遇到问题？</a></span>
                                                </div>

        <div class="login_hor clearfix">
                <label id = "label_captcha">验证码<em class="login_required"> *</em></label>
                <input id="inputCaptcha" type="text" autocomplete="off" name="inputCaptcha" checkstate="err" class="login_ipt iptw2" value="" onfocus="if(this.value=='') this.value = ''; this.select();" onblur="if(this.value=='') {this.value = ''; this.setAttribute('checkstate', 'err');}else{this.setAttribute('checkstate', 'ok');} "/>
                <img id='captcha' class="login_captcha" src="/ptlogin/captcha.do?captchaId=captchaReq7c0bca4caf072159886" onClick="javascript:UniLoginChangPIC('captchaReq7c0bca4caf072159886');"/>
                <span class="input_tip m-change-yzm">点击图片换一张</span>
        </div>

                                                <div class="login_hor clearfix"  style="display:none"></div>

                                                

                                                <div class="unilogin_box clearfix">
                                                        <input type="submit" value="" class="ptlogin_register" />
                                                        <a class="login_feedback" href="https://u.4399.com/kf/im/zcdl?ref=www_home" title="注册问题反馈" target="_blank">注册问题反馈</a>
                                                        <a class="register_foreign" href="https://u.4399.com/sso/intl/register.html?refer=/profile/realname.html" title="港澳台/海外用户注册" target="_blank">港澳台/海外用户注册></a>
                                                </div>
                                                <div class="login_hor clearfix">
                                                        <div class="login_tip flogin_tip">

                                                        <input id="reg_eula_agree" type="checkbox" name="reg_eula_agree" oncheck="checkInput(this,'reg_eula_agree')"><label id="reg_eula_info">已同意</label>

                                                        <div class="agr_arr" id="agrbtn">
                                                                <div class="agrbox" id="agrbox">
                                                                                <i class="wbor"></i>
                                                                                <span class="login_protocal">
                                                                                <a class="eual_link" target="_blank" href="https://ptlogin.4399.com/resource/protocol.html?type=1&aids=1,3,6,7">《用户协议》</a>
                                                                                和
                                                                                <a class="eual_link" target="_blank" href="https://ptlogin.4399.com/resource/protocol.html?type=2&aids=2,10">《隐私政策》</a>
                                                                                </span>
                                                                </div>
                                                        </div>
                                                        </div>
                                                        <div class="login_tip flogin_tip nflogin_tip">
                                                                <input id="login_autoLogin" type="checkbox" name="autoLogin" /><label for="login_autoLogin" id="reg_autoLogin_tip">自动登录</label>
                                                        </div>


                                                </div>
                                        </fieldset>
                                </form>
                                <script type="text/javascript">
                                        //快速注册框位置上移
                                        // if (parent.document.getElementById("loginDiv")) {
                                        //      var offset = 50;
                                        //      if (typeof(parent.unionLoginProps.__regFrameOffset) != 'undefined'){
                                        //              offset = parent.unionLoginProps.__regFrameOffset;
                                        //      }
                                        //      parent.document.getElementById("loginDiv").style.top = (parent.unionLoginProps.getPopupUcenterTop() - offset) + "px";
                                        // }

                                        try {document.reg_form.password.focus();} catch(err) {}
                                </script>
                                <script type="text/tmpl" id="fcaptchaTmpl">
                                         <div class="fdialog">
                                        <div class="dialog_hd">
                                            <h2 class="tit">请输入验证码</h2>
                                            <a href="javascript:void(0);" class="btn_close j-btn_close"></a>
                                        </div>
                                        <div class="dialog_bd">
                                            <div class="ftip j-ftip"></div>
                                            <div class="box_fipt">
                                                <input type="text" id="fCaptcha" autocomplete="off" name="fCaptcha" class="iptxt" value="" placeholder="请输入验证码" >
                                            </div>
                                            <div class="box_fimg clearfix">
                                                <img id="j-captcha1" class="login_captcha" src="http://ptlogin.4399.com/ptlogin/captcha.do?captchaId=<%= captchaId %>" captchaId="<%= captchaId %>" />
                                                <span class="input_tip">点击图片换一张</span>
                                            </div>
                                            <div class="box_opt">
                                                <a href="javascript:void(0);" class="btn_opt btn_cancel j-btn_close">取 消</a>
                                                <a href="javascript:void(0);" class="btn_opt btn_sure j-btn_sure">确定</a>
                                            </div>
                                        </div>
                                    </div>
                                </script>
                        </div>
                </div>
        </div>
</body>
<script type="text/javascript" src="//ptlogin.3304399.net/resource/jquery-1.4.4.min.js?v=296"></script>
<script type="text/javascript" src="//ptlogin.3304399.net/resource/ks.dialog.js?v=296"></script>
<script type="text/javascript" src="//ptlogin.3304399.net/resource/baiduTemplate.js?v=296"></script>
<script type="text/javascript" src="//ptlogin.3304399.net/resource/checkCookie.js?v=296"></script>

<script type="text/javascript" src="//ptlogin.3304399.net/resource/clipboard.min.js?v=296"></script>

        <script>
                if ("".length > 0) {
                        //document.getElementById("password").focus();
                }
        </script>
        <script type="text/javascript">
                if(Messenger.shouldOpen){
                        window.onload = function(){
                                msnger.emit("setIFrameHeight",{iframeId : "",height:document.body.offsetHeight});
                        }
                }
                eventHandles.initIFrameReady();
        </script>
<script type="text/javascript" src="//ptlogin.3304399.net/resource/regFrame.js?v=296"></script>
</html>

**Comment by dhwfrebhcjew** [comment]
新报错

**Comment by MCQTSS** [comment]
请自行查看项目源代码后debug，4399接口可能有变动或提交数据存在问题
